databases:
  - name: taobao-database
    plan: free

services:
  # The User Service
  - name: user-service
    type: web
    runtime: docker
    repo: https://github.com/oeunsoking6/TaobaoClone
    rootDir: ./backend/user-service
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taobao-database
          property: connectionString
      - key: JWT_SECRET
        sync: false

  # The Product Service
  - name: product-service
    type: web
    runtime: docker
    repo: https://github.com/oeunsoking6/TaobaoClone
    rootDir: ./backend/product-service
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taobao-database
          property: connectionString

  # The Recommendation Service
  - name: recommendation-service
    type: web
    runtime: docker
    repo: https://github.com/oeunsoking6/TaobaoClone
    rootDir: ./backend/recommendation-service
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taobao-database
          property: connectionString